

DEP = {
    "deti" : "deti-ap",
    "biblioteca" : "biblioteca-ap",
    "aauav" : "aauav-ap",
    "deca" : "deca-ap",
    "dbio" : "dbio-ap",
    "dmat" : "dmat-ap",
    "decivil" : "decivil-ap",
    "fis" : "fis-ap",
    "dem" : "dem-ap",
    "geo" : "geo-ap",
    "cpct" : "cpct-ap",
    "dcspt" : "dcspt-ap",
    "essua" : "essua-ap",
    "cicfano" : "cicfano-ap",
    "degeit" : "degeit-ap",
    "dq" : "dq-ap",
    "dao" : "dao-ap",
    "it" : "it-ap",
    "dep" : "dep-ap",
    "dlc" : "dlc-ap",
    "isca" : "isca-ap",
    "ietta" : "ietta-ap"
}

MAX_AP = {
    'deti': 23, 
    'biblioteca': 26,
    'aauav': 7,
    'dbio': 26,
    'deca': 19,
    'dmat': 26,
    'decivil': 8,
    'fis': 16,
    'dem': 20,
    'geo': 19,
    'cpct': 22,
    'dcspt': 14,
    'essua': 30,
    'cicfano': 11,
    'degeit': 21,
    'dq': 24,
    'it': 21,
    'dao': 17, 
    'dep': 19,
    'dlc': 15,
    'isca': 16,
    'ietta': 0
}

WIFIUSERS = {
    'deti': 0, 
    'biblioteca': 0,
    'aauav': 0,
    'dbio': 0,
    'deca': 0,
    'dmat': 0,
    'decivil': 0,
    'fis': 0,
    'dem': 0,
    'geo': 0,
    'cpct': 0,
    'dcspt': 0,
    'essua': 0,
    'cicfano': 0,
    'degeit': 0,
    'dq': 0,
    'it': 0,
    'dao': 0, 
    'dep': 0,
    'dlc': 0,
    'isca': 0,
    'ietta': 0
}